### API KEY USED FOR API-CALLS
api_key_users:
  -
# username: test_key_user
#   name: Test key User
#   role: API_KEY
#   api_key: test_key
# External authentication source
external_auth_url:  <%= ENV['AUTH_URL'] %>
#external_auth_url: "https://login-server.ub.gu.se/auth"
#cache_path: "/mnt/netapp/bilder/dflow/DLIVER_LAB_CACHE"
cache_path: <%= ENV['CACHE_PATH'] %>
#store_path: "/mnt/netapp/bilder/dflow/__STORE"
store_path: <%= ENV['STORE_PATH'] %>
#solr_url: "http://130.241.35.208:8983/solr/dliver-lab"
solr_url: <%= ENV['SOLR_URL'] %>
#thumbnail_file_group: "web"
thumbnail_file_group: <%= ENV['THUMBNAIL_FILE_GROUP'] %>
#default_thumbnail: "/mnt/netapp/bilder/dflow/DLIVER_LAB_CACHE/default_thumbnail.jpg"
default_thumbnail: <%= ENV['DEFAULT_THUMBNAIL']%>
