default: &default
  host: <%= ENV['DB_HOST'] %>
  port: 5432
  pool: 5
  timeout: 5000
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DB"] %>
  template: template0
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
development:
  <<: *default
production:
  <<: *default
staging:
  <<: *default